import React from 'react';
import Footer from './Base/Footer';
import Header from './Base/Header';
import './About.css';

function About() {
  return (
    <div className="About">
      <Header />
      <h1>About Sam</h1>
      <img src="https://www.fox21news.com/wp-content/uploads/sites/37/2021/08/baby-hippo.jpg?w=1280" alt="baby hippo" width="250" height="250" />
      <p>Sam, What are some Latin quotes?
Common Latin phrases you heard at least once
Veni, vidi, vici. I came, I saw, I conquered. ...
Alea iacta est. The die has been cast. ...
Carpe diem. Seize the day. ...
Cogito, ergo sum. I think, therefore I am. ...
In vino veritas. In wine, there is truth. ...
Et tu, Brute? “And you, Brutus?” ...
Acta non verba. ...
Carthago delenda est.</p>
    <h1>About Nicole</h1>
    <img src="https://www.fox21news.com/wp-content/uploads/sites/37/2021/08/baby-hippo.jpg?w=1280" alt="baby hippo" width="250" height="250"/>
    <p>What are some Latin quotes?
Common Latin phrases you heard at least once
Veni, vidi, vici. I came, I saw, I conquered. ...
Alea iacta est. The die has been cast. ...
Carpe diem. Seize the day. ...
Cogito, ergo sum. I think, therefore I am. ...
In vino veritas. In wine, there is truth. ...
Et tu, Brute? “And you, Brutus?” ...
Acta non verba. ...
Carthago delenda est.</p>


      <Footer />
    </div>
  );
}

export default About;
